# Generated by Django 3.0.7 on 2020-09-29 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200928_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ['-last_change']},
        ),
        migrations.AddField(
            model_name='dialog',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
