# Generated by Django 3.0.7 on 2020-09-29 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_user', '0005_auto_20200929_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
