# Generated by Django 3.1.2 on 2020-10-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_user', '0006_chatuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='image',
            field=models.ImageField(default='default/default.jpeg', upload_to='user_image'),
        ),
    ]
