# Generated by Django 3.0.7 on 2020-09-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='image',
            field=models.ImageField(default='', upload_to='user_image/'),
        ),
    ]
